services:
  - type: web
    name: magic-box-game-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /health

  - type: web
    name: magic-box-game-frontend
    env: static
    plan: free
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate 